# Generated by Django 6.0.6 on 2026-06-26 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Empresa')),
                ('rif', models.CharField(max_length=20, unique=True, verbose_name='RIF / Identificación')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección Física')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono de Contacto')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo de Contacto')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('identificacion', models.CharField(help_text='Identificación fiscal o personal. Debe ser única.', max_length=20, primary_key=True, serialize=False, verbose_name='RIF / Cédula')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Completo / Razón Social')),
                ('tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor')], default='CLIENTE', max_length=10, verbose_name='Tipo de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('red_social', models.CharField(blank=True, help_text='Ej: @usuario_instagram, +58... WhatsApp.', max_length=100, verbose_name='Usuario de Red Social')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('rif', models.CharField(blank=True, help_text='Solo requerido para contactos de tipo Proveedor.', max_length=20, null=True, verbose_name='RIF Proveedor')),
                ('nombre_asesor', models.CharField(blank=True, help_text='Contacto comercial directo del proveedor.', max_length=150, null=True, verbose_name='Nombre del Asesor de Ventas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='inventory.empresa')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos (Clientes y Proveedores)',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_bcv', models.DecimalField(decimal_places=4, default=0.0, help_text='Tasa oficial del Banco Central de Venezuela.', max_digits=12, verbose_name='Tasa BCV (Bs/$)')),
                ('tasa_mercado', models.DecimalField(decimal_places=4, default=0.0, help_text='Tasa de referencia informal (ej. Binance P2P).', max_digits=12, verbose_name='Tasa Mercado / Referencia (Bs/$)')),
                ('factor_cobertura', models.DecimalField(decimal_places=4, default=1.0, help_text='Calculado como: Tasa Mercado / Tasa BCV.', max_digits=8, verbose_name='Factor de Cobertura Cambiaria (Fc)')),
                ('margen_global', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='Margen de Ganancia Global (%)')),
                ('descuento_global', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Descuento Global (%)')),
                ('api_url', models.CharField(blank=True, help_text='Endpoint externo para sincronización automática de tasas.', max_length=500, verbose_name='URL de la API de Tasas')),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=4, verbose_name='Método HTTP')),
                ('response_selector', models.CharField(blank=True, help_text='Ruta dentro del JSON de respuesta (ej: data.prices.USDT).', max_length=200, verbose_name='Selector JSON Path')),
                ('print_offset_x', models.DecimalField(decimal_places=2, default=0.0, help_text='Desplazamiento horizontal global en milímetros.', max_digits=5, verbose_name='Offset X Impresión (mm)')),
                ('print_offset_y', models.DecimalField(decimal_places=2, default=0.0, help_text='Desplazamiento vertical global en milímetros.', max_digits=5, verbose_name='Offset Y Impresión (mm)')),
                ('print_row_spacing', models.DecimalField(decimal_places=2, default=5.0, help_text='Distancia vertical entre renglones de productos impresos.', max_digits=5, verbose_name='Espaciado de Filas (mm)')),
                ('usa_almacen_cuarentena', models.BooleanField(default=False, help_text='Desvía las devoluciones a un almacén de Servicio Técnico en lugar de reingresarlas al origen.', verbose_name='Usar Almacén de Cuarentena')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='inventory.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuración de la Empresa',
                'verbose_name_plural': 'Configuraciones de la Empresa',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaTasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Registro')),
                ('tasa_bcv', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Tasa BCV (Bs/$)')),
                ('tasa_mercado', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Tasa Mercado / Referencia (Bs/$)')),
                ('factor_cobertura', models.DecimalField(decimal_places=4, help_text='Fc = Tasa Mercado / Tasa BCV', max_digits=8, verbose_name='Factor de Cobertura Cambiaria (Fc)')),
                ('fuente', models.CharField(choices=[('MANUAL', 'Ingreso Manual'), ('API', 'Sincronización por API')], default='MANUAL', max_length=10, verbose_name='Fuente de la Tasa')),
                ('notas', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_tasas', to='inventory.empresa')),
            ],
            options={
                'verbose_name': 'Auditoría de Tasa de Cambio',
                'verbose_name_plural': 'Auditoría de Tasas de Cambio',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('sku', models.CharField(help_text='Código único interno de identificación del artículo.', max_length=50, primary_key=True, serialize=False, verbose_name='SKU')),
                ('codigo_proveedor', models.CharField(blank=True, max_length=100, verbose_name='Código de Proveedor')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Artículo')),
                ('categoria', models.CharField(choices=[('HOGAR', 'Hogar'), ('HERRAMIENTAS', 'Herramientas'), ('SOLARES', 'Solares'), ('OTROS', 'Otros')], default='OTROS', max_length=20, verbose_name='Categoría')),
                ('tipo', models.CharField(choices=[('FISICO', 'Físico'), ('COMBO', 'Combo Virtual')], default='FISICO', max_length=10, verbose_name='Tipo de Artículo')),
                ('usa_serial', models.BooleanField(default=False, help_text='Indica si este artículo requiere la selección obligatoria de seriales al facturar.', verbose_name='Usa Serial de Garantía')),
                ('costo', models.DecimalField(decimal_places=4, default=0.0, max_digits=14, verbose_name='Costo de Adquisición (USD)')),
                ('precio_divisa', models.DecimalField(decimal_places=4, default=0.0, max_digits=14, verbose_name='Precio en Divisas / Efectivo (USD)')),
                ('metodo_ganancia', models.CharField(choices=[('MARKUP', 'Markup (sobre el costo)'), ('MARGIN', 'Margen Real (sobre el precio de venta)')], default='MARKUP', max_length=10, verbose_name='Método de Cálculo de Ganancia')),
                ('margen_ind', models.DecimalField(decimal_places=2, default=30.0, help_text='Sobrescribe el margen global para este artículo.', max_digits=5, verbose_name='Margen / Markup Individual (%)')),
                ('descuento_ind', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Descuento Individual (%)')),
                ('cobertura_ind', models.DecimalField(blank=True, decimal_places=4, help_text='Si se configura, sobrescribe el Fc global del sistema.', max_digits=8, null=True, verbose_name='Factor de Cobertura Individual (Fc)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción General')),
                ('ficha_tecnica', models.TextField(blank=True, help_text='Especificaciones físicas y técnicas detalladas del artículo.', null=True, verbose_name='Ficha Técnica')),
                ('social_quick', models.TextField(blank=True, help_text='Mensaje comercial preformateado para Instagram/WhatsApp. Usar variables: [Precio_USD], [Precio_BCV], [Nombre_Articulo].', null=True, verbose_name='Respuesta Rápida de Redes')),
                ('social_cross', models.TextField(blank=True, help_text='Extracto corto para bloques de ofertas consolidadas.', null=True, verbose_name='Mensaje de Cross-Selling')),
                ('activo', models.BooleanField(default=True, help_text='Desactiva el artículo sin eliminarlo para preservar el historial del Kárdex.', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='inventory.empresa')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Identificador corto (ej: Principal, Sucursal Norte).', max_length=100, verbose_name='Nombre del Almacén')),
                ('es_principal', models.BooleanField(default=False, help_text='El almacén principal se asigna por defecto en importaciones masivas.', verbose_name='¿Es el Almacén Principal?')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacenes', to='inventory.empresa')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['-es_principal', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='InventarioAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cantidad Disponible')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Stock Mínimo (Punto de Reorden)')),
                ('ubicacion_estante', models.CharField(blank=True, help_text='Referencia física dentro del almacén (ej: Pasillo A, Estante 3).', max_length=50, verbose_name='Ubicación / Estante')),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización de Stock')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='inventory.almacen', verbose_name='Almacén')),
                ('articulo', models.ForeignKey(limit_choices_to={'tipo': 'FISICO'}, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='inventory.articulo', verbose_name='Artículo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='inventory.empresa')),
            ],
            options={
                'verbose_name': 'Inventario por Almacén',
                'verbose_name_plural': 'Inventarios por Almacén',
                'ordering': ['almacen', 'articulo'],
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_control', models.CharField(help_text='Identificador único de la Nota de Crédito.', max_length=50, verbose_name='Número de Control')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo de Devolución')),
                ('monto_total_reembolso', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Total de Reembolso (USD)')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='inventory.empresa')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
            },
        ),
        migrations.CreateModel(
            name='DetalleNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_aplicado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Aplicado al Reingreso')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='inventory.articulo')),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventory.notacredito')),
            ],
            options={
                'verbose_name': 'Detalle de Nota de Crédito',
                'verbose_name_plural': 'Detalles de Notas de Crédito',
            },
        ),
        migrations.CreateModel(
            name='NotaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Correlativo numérico único por empresa, generado automáticamente.', verbose_name='Nº de Nota de Entrega')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=10, verbose_name='Estado')),
                ('moneda_pago', models.CharField(choices=[('USD', 'Dólares (USD)'), ('BS_BCV', 'Bolívares a Tasa BCV'), ('BS_EFECTIVO', 'Bolívares en Efectivo')], default='USD', max_length=12, verbose_name='Moneda de Pago')),
                ('tasa_bcv_aplicada', models.DecimalField(decimal_places=4, default=0.0, help_text='Snapshot de la tasa BCV aplicada en el momento exacto de la venta.', max_digits=12, verbose_name='Tasa BCV al Momento de la Venta')),
                ('factor_cobertura_aplicado', models.DecimalField(decimal_places=4, default=1.0, max_digits=8, verbose_name='Factor de Cobertura Aplicado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_entrega', to='inventory.almacen', verbose_name='Almacén de Despacho')),
                ('cliente', models.ForeignKey(blank=True, help_text='Si está vacío, se asigna al cliente genérico.', limit_choices_to={'tipo': 'CLIENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_entrega', to='inventory.contacto', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_entrega', to='inventory.empresa')),
            ],
            options={
                'verbose_name': 'Nota de Entrega',
                'verbose_name_plural': 'Notas de Entrega',
                'ordering': ['-numero'],
            },
        ),
        migrations.AddField(
            model_name='notacredito',
            name='nota_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='inventory.notaentrega', verbose_name='Nota de Entrega Original'),
        ),
        migrations.CreateModel(
            name='MovimientoKardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=7, verbose_name='Tipo de Movimiento')),
                ('concepto', models.CharField(choices=[('COMPRA', 'Compra a Proveedor'), ('CARGA_MASIVA_SUMA', 'Carga Masiva — Suma'), ('CARGA_MASIVA_SUSTITUCION_ENTRADA', 'Carga Masiva — Entrada por Sustitución'), ('AJUSTE_ENTRADA', 'Ajuste Manual de Entrada'), ('TRANSFERENCIA_ENTRADA', 'Transferencia — Entrada'), ('DEVOLUCION_ENTRADA', 'Devolución — Reingreso'), ('REVERSO_ENTRADA', 'Reverso de Carga Masiva — Entrada'), ('VENTA', 'Venta (Nota de Entrega)'), ('CARGA_MASIVA_SUSTITUCION_SALIDA', 'Carga Masiva — Salida por Sustitución'), ('AJUSTE_SALIDA', 'Ajuste Manual de Salida'), ('TRANSFERENCIA_SALIDA', 'Transferencia — Salida'), ('MERMA_DEFECTUOSO', 'Merma por Artículo Defectuoso'), ('REVERSO_SALIDA', 'Reverso de Carga Masiva — Salida')], max_length=60, verbose_name='Concepto')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('saldo_resultante', models.DecimalField(decimal_places=2, help_text='Stock de este artículo en este almacén después del movimiento.', max_digits=12, verbose_name='Saldo Resultante')),
                ('lote_carga', models.CharField(blank=True, help_text='Referencia al batch de carga masiva que originó este movimiento.', max_length=100, verbose_name='ID de Lote de Carga Masiva')),
                ('detalle_adicional', models.TextField(blank=True, help_text='Información de auditoría extra (ej: factura de compra, referencia externa).', verbose_name='Detalle Adicional')),
                ('usuario', models.CharField(blank=True, max_length=150, verbose_name='Usuario que Realizó el Movimiento')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventory.almacen', verbose_name='Almacén')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventory.articulo', verbose_name='Artículo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_kardex', to='inventory.empresa')),
                ('nota_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_kardex', to='inventory.notaentrega', verbose_name='Nota de Entrega Asociada')),
            ],
            options={
                'verbose_name': 'Movimiento del Kárdex',
                'verbose_name_plural': 'Movimientos del Kárdex',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='DetalleNotaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('precio_unitario_usd', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Precio Unitario en USD (Snapshot)')),
                ('precio_unitario_bs', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Precio Unitario en Bs. (Snapshot)')),
                ('costo_unitario_snapshot', models.DecimalField(decimal_places=4, default=0.0, help_text='Costo de adquisición del artículo grabado inmutablemente al facturar (ADR-18).', max_digits=14, verbose_name='Costo Unitario al Momento de la Venta (Snapshot)')),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Descuento Aplicado (%)')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_nota_entrega', to='inventory.articulo', verbose_name='Artículo')),
                ('nota_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventory.notaentrega', verbose_name='Nota de Entrega')),
            ],
            options={
                'verbose_name': 'Detalle de Nota de Entrega',
                'verbose_name_plural': 'Detalles de Notas de Entrega',
            },
        ),
        migrations.CreateModel(
            name='RecetaCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Requerida por Unidad de Combo')),
                ('combo', models.ForeignKey(limit_choices_to={'tipo': 'COMBO'}, on_delete=django.db.models.deletion.CASCADE, related_name='receta_combo', to='inventory.articulo', verbose_name='Combo')),
                ('componente', models.ForeignKey(limit_choices_to={'tipo': 'FISICO'}, on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_combos', to='inventory.articulo', verbose_name='Componente Físico')),
            ],
            options={
                'verbose_name': 'Receta de Combo',
                'verbose_name_plural': 'Recetas de Combos',
            },
        ),
        migrations.CreateModel(
            name='SerialArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(help_text='Identificador de garantía único para esta unidad.', max_length=100, verbose_name='Serial / IMEI')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible en Mostrador'), ('VENDIDO', 'Vendido / Consumido')], default='DISPONIBLE', max_length=15, verbose_name='Estado Operativo')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seriales_almacenados', to='inventory.almacen', verbose_name='Almacén Actual')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seriales', to='inventory.articulo', verbose_name='Artículo')),
                ('detalle_nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seriales_asignados', to='inventory.detallenotaentrega', verbose_name='Nota de Venta Asociada')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seriales', to='inventory.empresa')),
            ],
            options={
                'verbose_name': 'Serial de Artículo',
                'verbose_name_plural': 'Seriales de Artículos',
            },
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['sku', 'activo'], name='idx_articulo_sku_activo'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['nombre'], name='idx_articulo_nombre'),
        ),
        migrations.AddIndex(
            model_name='inventarioalmacen',
            index=models.Index(fields=['articulo', 'almacen'], name='idx_inv_articulo_almacen'),
        ),
        migrations.AlterUniqueTogether(
            name='inventarioalmacen',
            unique_together={('articulo', 'almacen')},
        ),
        migrations.AlterUniqueTogether(
            name='notaentrega',
            unique_together={('empresa', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='recetacombo',
            unique_together={('combo', 'componente')},
        ),
        migrations.AlterUniqueTogether(
            name='serialarticulo',
            unique_together={('empresa', 'serial')},
        ),
    ]
