# Generated by Django 5.1.4 on 2026-06-26 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_normalizar_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacen',
            options={'ordering': ['-es_principal', 'nombre'], 'verbose_name': 'Almacén', 'verbose_name_plural': '03. Almacenes'},
        ),
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['nombre'], 'verbose_name': 'Artículo', 'verbose_name_plural': '05. Artículos'},
        ),
        migrations.AlterModelOptions(
            name='auditoriatasa',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Auditoría de Tasa de Cambio', 'verbose_name_plural': '08. Auditoría de Tasas de Cambio'},
        ),
        migrations.AlterModelOptions(
            name='configuracionempresa',
            options={'verbose_name': 'Configuración de la Empresa', 'verbose_name_plural': '02. Configuraciones de la Empresa'},
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['tipo', 'nombre'], 'verbose_name': 'Contacto', 'verbose_name_plural': '04. Contactos (Clientes y Proveedores)'},
        ),
        migrations.AlterModelOptions(
            name='detallenotacredito',
            options={'verbose_name': 'Detalle de Nota de Crédito', 'verbose_name_plural': '14. Detalles de Notas de Crédito'},
        ),
        migrations.AlterModelOptions(
            name='detallenotaentrega',
            options={'verbose_name': 'Detalle de Nota de Entrega', 'verbose_name_plural': '12. Detalles de Notas de Entrega'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': '01. Empresas'},
        ),
        migrations.AlterModelOptions(
            name='inventarioalmacen',
            options={'ordering': ['almacen', 'articulo'], 'verbose_name': 'Inventario por Almacén', 'verbose_name_plural': '09. Inventarios por Almacén'},
        ),
        migrations.AlterModelOptions(
            name='movimientokardex',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Movimiento del Kárdex', 'verbose_name_plural': '10. Movimientos del Kárdex'},
        ),
        migrations.AlterModelOptions(
            name='notacredito',
            options={'verbose_name': 'Nota de Crédito', 'verbose_name_plural': '13. Notas de Crédito'},
        ),
        migrations.AlterModelOptions(
            name='notaentrega',
            options={'ordering': ['-numero'], 'verbose_name': 'Nota de Entrega', 'verbose_name_plural': '11. Notas de Entrega'},
        ),
        migrations.AlterModelOptions(
            name='recetacombo',
            options={'verbose_name': 'Receta de Combo', 'verbose_name_plural': '06. Recetas de Combos'},
        ),
        migrations.AlterModelOptions(
            name='serialarticulo',
            options={'verbose_name': 'Serial de Artículo', 'verbose_name_plural': '07. Seriales de Artículos'},
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_activa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_activos', to='inventory.empresa', verbose_name='Empresa Activa')),
                ('empresas_permitidas', models.ManyToManyField(blank=True, related_name='usuarios_permitidos', to='inventory.empresa', verbose_name='Empresas Permitidas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': '02B. Perfiles de Usuario',
            },
        ),
    ]
