# Generated by Django 5.1.4 on 2026-06-26 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_perfil_usuario_rbac'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=100, verbose_name='Número de Factura')),
                ('fecha_compra', models.DateField(verbose_name='Fecha de Compra')),
                ('monto_total_usd', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Monto Total (USD)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_compra', to='inventory.empresa')),
                ('proveedor', models.ForeignKey(limit_choices_to={'tipo': 'PROVEEDOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_compra', to='inventory.contacto', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Documento de Compra',
                'verbose_name_plural': '12. Documentos de Compra',
                'ordering': ['-fecha_compra', '-id'],
            },
        ),
        migrations.AddField(
            model_name='movimientokardex',
            name='documento_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventory.documentocompra', verbose_name='Documento de Compra Asociado'),
        ),
    ]
