# Generated by Django 5.1.4 on 2026-06-26 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_modelo_documento_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocompra',
            name='estado',
            field=models.CharField(choices=[('PROCESADO', 'Procesado'), ('ANULADO', 'Anulado')], default='PROCESADO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='documentocompra',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Anulación'),
        ),
        migrations.AddField(
            model_name='notaentrega',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Anulación'),
        ),
        migrations.AddField(
            model_name='serialarticulo',
            name='compra_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seriales_ingresados', to='inventory.documentocompra'),
        ),
        migrations.AlterField(
            model_name='movimientokardex',
            name='concepto',
            field=models.CharField(choices=[('COMPRA', 'Compra a Proveedor'), ('CARGA_MASIVA_SUMA', 'Carga Masiva — Suma'), ('CARGA_MASIVA_SUSTITUCION_ENTRADA', 'Carga Masiva — Entrada por Sustitución'), ('AJUSTE_ENTRADA', 'Ajuste Manual de Entrada'), ('TRANSFERENCIA_ENTRADA', 'Transferencia — Entrada'), ('DEVOLUCION_ENTRADA', 'Devolución — Reingreso'), ('DEVOLUCION_VENTA', 'Devolución de Venta'), ('ANULACION_COMPRA', 'Anulación de Compra'), ('REVERSO_ENTRADA', 'Reverso de Carga Masiva — Entrada'), ('VENTA', 'Venta (Nota de Entrega)'), ('CARGA_MASIVA_SUSTITUCION_SALIDA', 'Carga Masiva — Salida por Sustitución'), ('AJUSTE_SALIDA', 'Ajuste Manual de Salida'), ('TRANSFERENCIA_SALIDA', 'Transferencia — Salida'), ('MERMA_DEFECTUOSO', 'Merma por Artículo Defectuoso'), ('REVERSO_SALIDA', 'Reverso de Carga Masiva — Salida')], max_length=60, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='notaentrega',
            name='estado',
            field=models.CharField(choices=[('PROCESADO', 'Procesado'), ('ANULADO', 'Anulado')], default='PROCESADO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='serialarticulo',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible en Mostrador'), ('VENDIDO', 'Vendido / Consumido'), ('ANULADO_COMPRA', 'Anulado por Reverso de Compra')], default='DISPONIBLE', max_length=15, verbose_name='Estado Operativo'),
        ),
    ]
