# Generated by Django 5.1.4 on 2026-06-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_perfeccionar_reversos_trazables'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='cross_selling_footer',
            field=models.TextField(default='¡Envíame un mensaje para coordinar tu pedido ahora mismo! 🚀', help_text='Texto que cierra el mensaje de oferta consolidada en el Panel de Social Selling.', verbose_name='Pie de Oferta Consolidada'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='cross_selling_header',
            field=models.TextField(default='🔥 *SUPER OFERTA CONSOLIDADA A2LT* 🔥\n\nTenemos estos productos listos para ti:\n\n', help_text='Texto que encabeza el mensaje de oferta consolidada en el Panel de Social Selling.', verbose_name='Encabezado Oferta Consolidada'),
        ),
    ]
