# Generated by Django 5.1.4 on 2026-06-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inicializar_configuraciones_existentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': '04a. Clientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.contacto',),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': '04b. Proveedores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.contacto',),
        ),
        migrations.AddField(
            model_name='documentocompra',
            name='observaciones',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones'),
        ),
    ]
