# Generated by Django 5.1.4 on 2026-06-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_add_observaciones_to_documento_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocompra',
            name='fecha_compra',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de Compra'),
        ),
        migrations.AlterField(
            model_name='documentocompra',
            name='numero_factura',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Número de Factura'),
        ),
    ]
