# Generated by Django 6.0.6 on 2026-07-10 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_make_factura_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocompra',
            name='factor_cobertura_aplicado',
            field=models.DecimalField(blank=True, decimal_places=4, default=1.0, max_digits=8, null=True, verbose_name='Factor cobertura aplicada (snapshot)'),
        ),
        migrations.AddField(
            model_name='documentocompra',
            name='fuente_tasa',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Fuente de la tasa (BCV/MANUAL/BINANCE)'),
        ),
        migrations.AddField(
            model_name='documentocompra',
            name='monto_total_bs_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Monto total en Bs (snapshot)'),
        ),
        migrations.AddField(
            model_name='documentocompra',
            name='tasa_bcv_aplicada',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=12, null=True, verbose_name='Tasa BCV aplicada (snapshot)'),
        ),
        migrations.AddField(
            model_name='documentocompra',
            name='tasa_mercado_aplicada',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=12, null=True, verbose_name='Tasa mercado aplicada (snapshot)'),
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Por ejemplo: USD, VES, EUR, COP, ARS', max_length=3, verbose_name='Codigo ISO 4217')),
                ('nombre', models.CharField(max_length=50)),
                ('simbolo', models.CharField(default='$', max_length=5)),
                ('decimales', models.PositiveSmallIntegerField(default=2)),
                ('es_base', models.BooleanField(default=False, help_text='Si True, todos los precios se almacenan en esta moneda.', verbose_name='Moneda base del tenant')),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monedas', to='inventory.empresa')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['es_base', 'codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Tasa (1 origen = N destino)')),
                ('fecha', models.DateField(verbose_name='Fecha de la tasa')),
                ('fuente', models.CharField(choices=[('BCV', 'Banco Central de Venezuela (oficial)'), ('MANUAL', 'Ingreso manual del operador'), ('API', 'API externa (e.g. Binance P2P)'), ('INFLATION', 'Tasa calculada por inflacion interna')], default='MANUAL', max_length=20)),
                ('usuario', models.CharField(blank=True, default='', max_length=150)),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas_cambio', to='inventory.empresa')),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasas_destino', to='inventory.moneda')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasas_origen', to='inventory.moneda')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-fecha', '-creada_en'],
                'indexes': [models.Index(fields=['empresa', 'moneda_origen', 'moneda_destino', '-fecha'], name='inventory_t_empresa_068cdc_idx')],
            },
        ),
    ]
