# Generated by Django 5.1.4 on 2026-07-11 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_documentocompra_factor_cobertura_aplicado_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notaentrega',
            unique_together={('empresa', 'numero')},
        ),
        migrations.RemoveField(
            model_name='detallenotaentrega',
            name='precio_unitario_bs',
        ),
        migrations.RemoveField(
            model_name='detallenotaentrega',
            name='precio_unitario_usd',
        ),
        migrations.AddField(
            model_name='articulo',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=16.0, help_text='Editable sólo por usuarios superiores en la Ficha. Snapshot inmutable al facturar.', max_digits=5, verbose_name='IVA del Artículo (%)'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='correlativo_inicial_nota',
            field=models.PositiveIntegerField(default=1, help_text='Número inicial del correlativo. Para migraciones puede arrancar desde N.', verbose_name='Correlativo Inicial Nota'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='ivas_disponibles',
            field=models.JSONField(blank=True, default=list, help_text='Lista de hasta 5 tasas de IVA configurables. Ej: [0, 8, 16].', verbose_name='IVAs Disponibles (%)'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='prefijo_nota_entrega',
            field=models.CharField(default='NE', help_text='Prefijo alfanumérico fijo para el correlativo. Ej: NE, A2LT-B17.', max_length=20, verbose_name='Prefijo Nota de Entrega'),
        ),
        migrations.AddField(
            model_name='detallenotaentrega',
            name='almacen',
            field=models.ForeignKey(blank=True, help_text='Almacén desde donde se ejecuta la rebaja real de stock.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_nota_entrega', to='inventory.almacen', verbose_name='Almacén de Origen'),
        ),
        migrations.AddField(
            model_name='detallenotaentrega',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Snapshot del IVA tomado de la ficha del artículo al facturar.', max_digits=5, verbose_name='IVA del Artículo (%) (Snapshot)'),
        ),
        migrations.AddField(
            model_name='detallenotaentrega',
            name='precio_ajustado',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='precio_base × factor_cobertura. Protección cambiaria.', max_digits=14, verbose_name='Precio Ajustado (USD, Snapshot)'),
        ),
        migrations.AddField(
            model_name='detallenotaentrega',
            name='precio_ajustado_bcv',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='precio_base × factor_cobertura × tasa_bcv. Mayor protección.', max_digits=16, verbose_name='Precio Bs. Ajustado (Snapshot)'),
        ),
        migrations.AddField(
            model_name='detallenotaentrega',
            name='precio_base',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Precio en divisas del catálogo al momento de facturar.', max_digits=14, verbose_name='Precio Base (USD, Snapshot)'),
        ),
        migrations.AddField(
            model_name='detallenotaentrega',
            name='precio_directo_bcv',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='precio_base × tasa_bcv. Sin factor de cobertura.', max_digits=16, verbose_name='Precio Bs. BCV (Snapshot)'),
        ),
        migrations.AddField(
            model_name='notaentrega',
            name='descuento_global',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Descuento Global del Documento (%)'),
        ),
        migrations.AddField(
            model_name='notaentrega',
            name='iva_check',
            field=models.BooleanField(default=False, help_text='Indica si el documento procesa el cálculo impositivo.', verbose_name='IVA Aplicado'),
        ),
        migrations.AddField(
            model_name='notaentrega',
            name='iva_total',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Snapshot del IVA totalizado al momento de la venta.', max_digits=14, verbose_name='IVA Total (Snapshot)'),
        ),
        migrations.AddField(
            model_name='notaentrega',
            name='numero_factura',
            field=models.CharField(blank=True, default='', help_text='Manual. Sólo si tipo_documento=FACTURA. Único por empresa.', max_length=100, verbose_name='N° Factura Física'),
        ),
        migrations.AddField(
            model_name='notaentrega',
            name='numero_nota',
            field=models.CharField(blank=True, help_text='Correlativo alfanumérico configurable. Ej: NE-00000008.', max_length=30, verbose_name='N° Nota Interna'),
        ),
        migrations.AddField(
            model_name='notaentrega',
            name='tasa_mercado_aplicada',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='Tasa Mercado al Momento de la Venta (Snapshot)'),
        ),
        migrations.AddField(
            model_name='notaentrega',
            name='tipo_documento',
            field=models.CharField(choices=[('NOTA_ENTREGA', 'Nota de Entrega'), ('FACTURA', 'Factura')], default='NOTA_ENTREGA', max_length=15, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='detallenotaentrega',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Descuento Individual (%)'),
        ),
        migrations.AlterUniqueTogether(
            name='notaentrega',
            unique_together={('empresa', 'numero'), ('empresa', 'numero_nota')},
        ),
    ]
