# Generated by Django 5.1.4 on 2026-07-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_notaentrega_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notaentrega',
            unique_together={('empresa', 'numero')},
        ),
        migrations.AddConstraint(
            model_name='notaentrega',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_nota', ''), _negated=True), fields=('empresa', 'numero_nota'), name='unique_numero_nota_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='notaentrega',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_factura', ''), _negated=True), fields=('empresa', 'numero_factura'), name='unique_numero_factura_por_empresa'),
        ),
    ]
