# Generated by Django 5.1.4 on 2026-07-12 01:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_notaentrega_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleDocumentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Cantidad')),
                ('costo_base', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Costo Factura ($)')),
                ('costo_ajustado', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Costo Ajustado ($)')),
                ('costo_directo_bcv', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Costo Directo BCV (Bs)')),
                ('costo_ajustado_bcv', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Costo Ajustado BCV (Bs)')),
                ('costo_unitario_snapshot', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Costo Promedio Snapshot ($)')),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Descuento Individual (%)')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5, verbose_name='IVA (%)')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': '13. Detalles de Compras',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='correlativo_inicial_factura_compra',
            field=models.PositiveIntegerField(default=1, help_text='Número inicial del correlativo de facturas de compra.', verbose_name='Correlativo Inicial Factura Compra'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='prefijo_factura_compra',
            field=models.CharField(default='FC', help_text='Prefijo alfanumérico fijo para el correlativo de facturas de compra. Ej: FC, COM.', max_length=20, verbose_name='Prefijo Factura Compra'),
        ),
        migrations.AddField(
            model_name='documentocompra',
            name='descuento_global',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento global sobre el documento (0-100).', max_digits=5, verbose_name='Descuento Global (%)'),
        ),
        migrations.AddField(
            model_name='documentocompra',
            name='iva_total',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Suma de IVA de cada ítem en USD.', max_digits=14, verbose_name='IVA Total (USD)'),
        ),
        migrations.AddField(
            model_name='documentocompra',
            name='numero',
            field=models.PositiveIntegerField(default=0, help_text='Número secuencial entero por empresa (no mostrar al usuario, usar numero_interno).', verbose_name='Correlativo'),
        ),
        migrations.AddField(
            model_name='documentocompra',
            name='numero_interno',
            field=models.CharField(blank=True, default='', help_text='Correlativo auto-generado: prefijo + número secuencial.', max_length=50, verbose_name='N° Interno'),
        ),
        migrations.AddField(
            model_name='documentocompra',
            name='tipo_documento',
            field=models.CharField(choices=[('FACTURA_COMPRA', 'Factura de Compra'), ('NOTA_CREDITO_COMPRA', 'Nota de Crédito de Compra'), ('ORDEN_COMPRA', 'Orden de Compra')], default='FACTURA_COMPRA', max_length=20, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='documentocompra',
            name='numero_factura',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='N° Factura Proveedor'),
        ),
        migrations.AddConstraint(
            model_name='documentocompra',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_factura__gt', '')), fields=('empresa', 'numero_factura'), name='unique_numero_factura_compra_per_empresa'),
        ),
        migrations.AddConstraint(
            model_name='documentocompra',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_interno__gt', '')), fields=('empresa', 'numero_interno'), name='unique_numero_interno_compra_per_empresa'),
        ),
        migrations.AddField(
            model_name='detalledocumentocompra',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='inventory.almacen'),
        ),
        migrations.AddField(
            model_name='detalledocumentocompra',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='inventory.articulo'),
        ),
        migrations.AddField(
            model_name='detalledocumentocompra',
            name='documento_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventory.documentocompra'),
        ),
    ]
