# Generated by Django 5.1.4 on 2026-07-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_detalledocumentocompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocompra',
            name='numero_factura',
            field=models.CharField(blank=True, default='', help_text='N° de factura, nota de entrega o recibo del proveedor. Obligatorio para FACTURA_COMPRA; opcional para NOTA_ENTREGA_PROVEEDOR y REGISTRO_MENOR. Único por empresa cuando no es vacío.', max_length=100, verbose_name='N° Documento Proveedor'),
        ),
        migrations.AlterField(
            model_name='documentocompra',
            name='tipo_documento',
            field=models.CharField(choices=[('FACTURA_COMPRA', 'Factura de Compra'), ('NOTA_ENTREGA_PROVEEDOR', 'Nota de Entrega / Recibo'), ('REGISTRO_MENOR', 'Registro Menor (sin doc.)')], default='FACTURA_COMPRA', max_length=30, verbose_name='Tipo de Documento'),
        ),
    ]
