# Generated by Django 5.1.4 on 2026-07-13 19:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_tipo_documento_compra_3_opciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallenotacredito',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detallenotacredito',
            name='costo_aplicado',
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='correlativo_inicial_nota_credito',
            field=models.PositiveIntegerField(default=1, help_text='Número inicial del correlativo de NCs.', verbose_name='Correlativo Inicial Nota de Crédito'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='prefijo_nota_credito',
            field=models.CharField(default='NC', help_text='Prefijo alfanumérico fijo para el correlativo. Ej: NC, DEV.', max_length=20, verbose_name='Prefijo Nota de Crédito'),
        ),
        migrations.AddField(
            model_name='detallenotacredito',
            name='almacen',
            field=models.ForeignKey(blank=True, help_text='Almacén donde reingresa el stock; usualmente el del doc. origen. Obligatorio al persistir (enforced por clean()).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_nota_credito', to='inventory.almacen', verbose_name='Almacén (reingreso)'),
        ),
        migrations.AddField(
            model_name='detallenotacredito',
            name='cantidad_devuelta',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Cantidad del detalle origen que se devuelve. Validada contra cantidad pendiente_devolver.', max_digits=14, verbose_name='Cantidad Devuelta'),
        ),
        migrations.AddField(
            model_name='detallenotacredito',
            name='detalle_origen_compra',
            field=models.ForeignKey(blank=True, help_text='Solo si NC es de COMPRA. Snapshot inmutable del original.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='inventory.detalledocumentocompra', verbose_name='Detalle de Compra Origen'),
        ),
        migrations.AddField(
            model_name='detallenotacredito',
            name='detalle_origen_venta',
            field=models.ForeignKey(blank=True, help_text='Solo si NC es de VENTA. Snapshot inmutable del original.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='inventory.detallenotaentrega', verbose_name='Detalle de Venta Origen'),
        ),
        migrations.AddField(
            model_name='detallenotacredito',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='detallenotacredito',
            name='iva_porcentaje_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Snapshot tomado del detalle origen o editado por negociación.', max_digits=5, verbose_name='IVA % (Snapshot)'),
        ),
        migrations.AddField(
            model_name='detallenotacredito',
            name='iva_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='subtotal_devuelto_usd × iva_porcentaje_snapshot / 100.', max_digits=16, verbose_name='IVA del Item Devuelto (USD)'),
        ),
        migrations.AddField(
            model_name='detallenotacredito',
            name='linea_total_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='subtotal_devuelto_usd + iva_usd.', max_digits=16, verbose_name='Total Línea (USD)'),
        ),
        migrations.AddField(
            model_name='detallenotacredito',
            name='precio_unitario_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Snapshot tomado del detalle origen o editado por negociación.', max_digits=14, verbose_name='Precio Unitario (Snapshot)'),
        ),
        migrations.AddField(
            model_name='detallenotacredito',
            name='subtotal_devuelto_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='~(cantidad_devuelta × precio_unitario_snapshot) - descuento (0% por defecto).', max_digits=16, verbose_name='Subtotal Devuelto (USD)'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='doc_origen_tipo',
            field=models.CharField(choices=[('VENTA', 'Venta'), ('COMPRA', 'Compra')], default='VENTA', max_length=10, verbose_name='Tipo de documento origen'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='estado',
            field=models.CharField(choices=[('PROCESADO', 'Procesado'), ('ANULADO', 'Anulado')], default='PROCESADO', max_length=10, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='factura_compra',
            field=models.ForeignKey(blank=True, help_text='Solo si la NC es de COMPRA (devolución al proveedor).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='inventory.documentocompra', verbose_name='Documento de Compra Original'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='motivo_anulacion',
            field=models.TextField(blank=True, default='', help_text='Si el estado es ANULADO, explica por qué.', verbose_name='Motivo de Anulación'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='numero',
            field=models.PositiveIntegerField(default=0, help_text='Secuencial entero por empresa (no mostrar al usuario).', verbose_name='Correlativo'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='prefijo',
            field=models.CharField(default='NC', help_text='Definido por ConfiguracionEmpresa.prefijo_nota_credito (default "NC").', max_length=20, verbose_name='Prefijo de NC'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='usuario',
            field=models.CharField(default='Sistema', max_length=150, verbose_name='Usuario que emitió la NC'),
        ),
        migrations.AlterField(
            model_name='detallenotacredito',
            name='articulo',
            field=models.ForeignKey(help_text='Redundante para query speed; debe coincidir con el detalle origen.', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_nota_credito', to='inventory.articulo', verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='detallenotacredito',
            name='nota_credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventory.notacredito', verbose_name='Nota de Crédito'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='monto_total_reembolso',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Suma de (cantidad_devuelta × precio_unitario_snapshot) + IVA.', max_digits=16, verbose_name='Monto Total de Reembolso (USD)'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='motivo',
            field=models.TextField(help_text='Motivo GLOBAL (R6). Obligatorio, no blank.', verbose_name='Motivo de Devolución'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='nota_entrega',
            field=models.ForeignKey(blank=True, help_text='Solo si la NC es de VENTA (devolución del cliente).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='inventory.notaentrega', verbose_name='Nota de Entrega Original'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='numero_control',
            field=models.CharField(blank=True, default='', help_text='Formato de display: "{prefijo}-{numero:08d}". Auto-asignado en save().', max_length=50, verbose_name='N° Control NC'),
        ),
        migrations.AddConstraint(
            model_name='detallenotacredito',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('detalle_origen_compra__isnull', True), ('detalle_origen_venta__isnull', False)), models.Q(('detalle_origen_compra__isnull', False), ('detalle_origen_venta__isnull', True)), _connector='OR'), name='detalle_nc_un_origen_exacto'),
        ),
        migrations.AddConstraint(
            model_name='notacredito',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('factura_compra__isnull', True), ('nota_entrega__isnull', False)), models.Q(('factura_compra__isnull', False), ('nota_entrega__isnull', True)), _connector='OR'), name='nota_credito_un_origen_exacto'),
        ),
    ]
