# Generated by Django 5.1.4 on 2026-07-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_nota_credito_devoluciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacredito',
            name='prefijo',
            field=models.CharField(default='', help_text='Si está vacío, save() lo lee de ConfiguracionEmpresa.prefijo_nota_credito (default "NC").', max_length=20, verbose_name='Prefijo de NC'),
        ),
    ]
